networks:
  postgres:
    external: true

services:
  postgres:
    image: postgres:latest
    container_name: sample-private-db
    restart: always
    env_file:
      - ./envs/mac/postgres.env
    volumes:
      - ./certs/server.cert:/certs/server.cert:ro
      - ./certs/postgres_cert.key:/certs/server.key:ro
    ports:
      - 5432:5432
      - 5433:443

  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: always
    env_file:
      - ./envs/mac/pgadmin.env
    volumes:
      - ./certs/server.cert:/certs/server.cert:ro
      - ./certs/postgres_cert.key:/certs/server.key:ro
    ports:
      - 5001:80
      - 5002:443

  smtp:
    image: ${DOCKER_REGISTRY-}smpt4dev
    container_name: smtp4dev
    build:
      context: "smtp4dev"
      dockerfile: "Dockerfile"
    restart: always
    env_file:
      - ./envs/mac/mail.env
    ports:
      - 5090:80
      - 5091:443
      - 25:25
      - 587:587
      - 143:143
    volumes:
      - ./certs:/home/app/.aspnet/https:ro
      # This is where smtp4dev stores the database..
      - ./data/smtp4dev-data:/smtp4dev
    environment:
      # Uncomment to customise these settings
      # This is not a complete list of the available settings.
      # See the documentation in appsettings.json for a full list.

      #Specifies the virtual path from web server root where SMTP4DEV web interface will be hosted. e.g. "/" or "/smtp4dev"
      #- ServerOptions__BasePath=/smtp4dev

      #Specifies the URLs the web UI will use inside the container.
      - ServerOptions__Urls=http://*:80;https://*:443

      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

      #Locks settings from being changed by user via web interface
      #- ServerOptions__LockSettings=true

      #Specifies the path where the database will be stored relative to APPDATA env var on Windows or XDG_CONFIG_HOME on non-Windows. Specify "" to use an in memory database.
      #- ServerOptions__Database=database.db

      #Specifies the number of messages to keep
      #- ServerOptions__NumberOfMessagesToKeep=100

      #Specifies the number of sessions to keep
      #- ServerOptions__NumberOfSessionsToKeep=100

      #Specifies the TLS mode to use. None=Off. StartTls=On demand if client supports STARTTLS. ImplicitTls=TLS as soon as connection is established.
      - ServerOptions__TlsMode=StartTls

      #Specifies the TLS certificate to use if TLS is enabled/requested. Specify "" to use an auto-generated self-signed certificate (then see console output on first startup)
      - ServerOptions__TlsCertificate=/home/app/.aspnet/https/aspnetapp.pfx
      - ServerOptions__TlsCertificatePassword=changeit

      #Specifies a mailbox with name "Test" and recipient "hello@world.com". To add more, use the same format but replace the number at the end of the variable name.
      #- ServerOptions__Mailboxes__0=Test=hello@world.com

      #Sets the name of the SMTP server that will be used to relay messages or "" if messages should not be relayed
      #- RelayOptions__SmtpServer=

      #Sets the port number for the SMTP server used to relay messages.
      #- RelayOptions__SmtpPort=25

      #Specifies a comma separated list of recipient addresses for which messages will be relayed. An empty list means that no messages are relayed.
      #- RelayOptions__AllowedEmailsString=

      #Specifies the address used in MAIL FROM when relaying messages. (Sender address in message headers is left unmodified). The sender of each message is used if not specified.
      #- RelayOptions__SenderAddress=

      #The username for the SMTP server used to relay messages. If "" no authentication is attempted.
      #- RelayOptions__Login=

      #The password for the SMTP server used to relay messages
      #- RelayOptions__Password=

      #Specifies the port the IMAP server will listen on - allows standard email clients to view/retrieve messages
      #"ServerOptions__ImapPort"=143

volumes:
  smtp4dev-data:
